all:
	@echo "Hello" # @ before command to stop it from being printed
	
	# cd command does not affect, because each command is effectively runs in a new shell
	cd ..
	@echo `pwd`

	# solution
	cd ..; \
	echo `pwd`

